### ISSUE TITLE
EPP loading articles is broken, causing the server to crash

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-server#336]
# Description

loading articles fails on the cluster with a duplicate ID error:

```
> kubectl logs -n epp epp-node-796b947999-xwfxk 
Defaulted container "epp-node" out of: epp-node, git-sync, create-user (init)
yarn run v1.22.19
$ ts-node src/server.ts
{"level":"info","message":"Example app listening on port 3000"}
{"time":"2022-09-09T07:37:28.198Z","tag":"encoda:jats","level":1,"message":"Using default decoding for JATS element name: "preformat""}
{"time":"2022-09-09T07:37:29.033Z","tag":"encoda","level":1,"message":"html:encode Properties of `Article` not supported: `dateReceived`, `dateAccepted`, `isPartOf`, `licenses`, `meta`"}
{"time":"2022-09-09T07:37:29.047Z","tag":"encoda","level":1,"message":"html:encode Properties of `Person` not supported: `honorificSuffix`"}
{"time":"2022-09-09T07:37:29.643Z","tag":"encoda:jats","level":1,"message":"Using default decoding for JATS element name: "email""}
{"time":"2022-09-09T07:37:29.691Z","tag":"encoda","level":1,"message":"html:encode Properties of `Article` not supported: `dateReceived`, `dateAccepted`, `isPartOf`, `licenses`, `meta`"}
{"time":"2022-09-09T07:37:29.993Z","tag":"encoda","level":1,"message":"html:encode Properties of `Article` not supported: `dateReceived`, `dateAccepted`, `isPartOf`, `licenses`, `meta`"}
{"time":"2022-09-09T07:37:30.099Z","tag":"encoda","level":1,"message":"html:encode Properties of `Article` not supported: `dateReceived`, `dateAccepted`, `isPartOf`, `licenses`, `meta`"}
{"time":"2022-09-09T07:37:30.254Z","tag":"encoda","level":1,"message":"html:encode Properties of `Article` not supported: `dateReceived`, `dateAccepted`, `isPartOf`, `licenses`, `meta`"}
{"time":"2022-09-09T07:37:30.389Z","tag":"encoda:jats","level":1,"message":"Using default decoding for JATS element name: "preformat""}
{"level":"debug","message":"replacing /opt/articles-data/9839de42efe4a1e22b2c7c354ca6c0b231a72ee6/data/10.1101/2020.04.07.030213 in JSON and HTML with /article/10.1101/2020.04.07.030213/attachment for IIIF server"}
{"level":"debug","message":"replacing /opt/articles-data/9839de42efe4a1e22b2c7c354ca6c0b231a72ee6/data/10.1101/2021.12.08.471796 in JSON and HTML with /article/10.1101/2021.12.08.471796/attachment for IIIF server"}
{"time":"2022-09-09T07:37:31.596Z","tag":"encoda:jats","level":1,"message":"Using default decoding for JATS element name: "email""}
{"level":"debug","message":"replacing /opt/articles-data/9839de42efe4a1e22b2c7c354ca6c0b231a72ee6/data/10.1101/2021.11.17.469032 in JSON and HTML with /article/10.1101/2021.11.17.469032/attachment for IIIF server"}
{"level":"debug","message":"replacing /opt/articles-data/9839de42efe4a1e22b2c7c354ca6c0b231a72ee6/data/10.1101/2022.03.15.484463 in JSON and HTML with /article/10.1101/2022.03.15.484463/attachment for IIIF server"}
/opt/epp/node_modules/mongodb/src/sdam/server.ts:456
      return callback(undefined, result);
             ^
MongoServerError: E11000 duplicate key error collection: epp.articles index: _id_ dup key: { _id: "10.1101/2020.04.07.030213" }
    at /opt/epp/node_modules/mongodb/src/operations/insert.ts:85:25
    at /opt/epp/node_modules/mongodb/src/cmap/connection_pool.ts:518:13
    at /opt/epp/node_modules/mongodb/src/sdam/server.ts:371:13
    at handleOperationResult (/opt/epp/node_modules/mongodb/src/sdam/server.ts:456:14)
    at Connection.onMessage (/opt/epp/node_modules/mongodb/src/cmap/connection.ts:450:5)
    at MessageStream.<anonymous> (/opt/epp/node_modules/mongodb/src/cmap/connection.ts:256:56)
    at MessageStream.emit (node:events:513:28)
    at MessageStream.emit (node:domain:489:12)
    at processIncomingData (/opt/epp/node_modules/mongodb/src/cmap/message_stream.ts:193:14)
    at MessageStream._write (/opt/epp/node_modules/mongodb/src/cmap/message_stream.ts:70:5) {
  index: 0,
  code: 11000,
  keyPattern: { _id: 1 },
  keyValue: { _id: '10.1101/2020.04.07.030213' },
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by scottaubrey** [comment]
fixed in #335
